# ==================================================================
# module list
# ------------------------------------------------------------------
# system        18.04.3  ubuntu
# python        3.6.8    (apt)
# tensorflow    1.15.0   (pip)
# ==================================================================

FROM tensorflow/tensorflow:1.15.0-py3-jupyter

## Replace pip.conf
RUN mkdir -p /root/.pip/
COPY pip.conf /root/.pip

## Replace sources.list
RUN mv /etc/apt/sources.list  /etc/apt/sources.list~
COPY sources.list.ubuntu18 /etc/apt/sources.list

RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    PIP_INSTALL="python -m pip3 --no-cache-dir install --upgrade" && \
    GIT_CLONE="git clone --depth 10" && \

    rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \

    apt-get update && \

# ==================================================================
# tools
# ------------------------------------------------------------------

    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        build-essential \
        ca-certificates \
        cmake \
        wget \
		curl \
        git \
        vim \
		gcc \
		g++

WORKDIR /home
